"""
Candidate profile constant for GovIntel AI.
Used across AI matching, scoring, qualification, and recommendation services.
"""

CANDIDATE_PROFILE = {
    "name": "Manoj Kumar",
    "current_role": "Vice President – Digital & Advisory",
    "years_experience": 17,
    "summary": (
        "Vice President – Digital & Advisory with 17+ years of experience in Government "
        "Consulting, Public Sector Advisory, Digital Transformation, and AI-led Governance. "
        "Held leadership roles at Rodic Consultants, Primus Partners, PwC India, Deloitte India, "
        "NISG, and TCIL. Deep expertise in PMU setup, programme management, procurement advisory, "
        "bid management, DPR preparation, RFP development, technical evaluation, vendor management, "
        "and business development for central and state government clients, with substantial "
        "multilateral exposure across World Bank, ADB, JICA, and AIIB funded programmes."
    ),
    "previous_organizations": [
        "Rodic Consultants",
        "Primus Partners",
        "PwC India",
        "Deloitte India",
        "NISG",
        "TCIL",
    ],
    "core_competencies": [
        "Government Consulting",
        "Public Sector Advisory",
        "Digital Transformation",
        "AI-led Governance",
        "PMU Setup",
        "Programme Management",
        "Procurement Advisory",
        "Bid Management",
        "DPR Preparation",
        "RFP Development",
        "Technical Evaluation",
        "Vendor Management",
        "Business Development",
        "Proposal Management",
        "Stakeholder Management & Facilitation",
        "Change Management",
        "Capacity Building & Training",
        "Monitoring & Evaluation (M&E)",
    ],
    "technical_skills": [
        "MS Project", "Power BI", "Excel / Advanced Analytics", "SharePoint",
        "GIS / QGIS", "SAP (project oversight)", "ERP systems (project oversight)",
        "AI / Machine Learning frameworks (conceptual & governance)",
        "Cloud platforms (AWS, Azure, GCP — project oversight)",
        "Procurement management systems (GeM, e-Procurement)",
    ],
    "domain_expertise": [
        "Digital Health",
        "Public Finance",
        "Infrastructure",
        "Smart Governance",
        "Power Sector",
        "Policing",
        "Postal Modernization",
    ],
    "multilateral_experience": ["World Bank", "ADB", "JICA", "AIIB"],
    "preferred_employers": [
        "World Bank", "ADB", "JICA", "AIIB", "UNDP", "UNICEF", "WHO", "GIZ", "FCDO",
        "Deloitte", "PwC", "EY", "KPMG", "McKinsey", "BCG", "Accenture",
        "IBM Consulting", "Rodic Consultants", "Primus Partners", "NISG", "TCIL",
        "MeitY", "NIC", "State Governments", "NASSCOM",
    ],
    "preferred_roles": [
        "Vice President", "Director", "Associate Partner", "Partner",
        "Practice Head", "Government Consulting Lead", "Public Sector Lead",
        "Digital Transformation Lead", "Advisory Lead", "Practice Lead",
    ],
    "target_leadership_titles": [
        "vp", "vice president", "director", "associate partner", "partner",
        "practice head", "practice lead", "government consulting lead",
        "public sector lead", "public sector consulting lead",
        "digital transformation lead", "advisory lead",
    ],
    "preferred_locations": ["Delhi", "Gurgaon", "Gurugram", "Noida", "Greater Noida", "Ghaziabad", "Faridabad"],
    "ncr_locations": ["delhi", "new delhi", "gurgaon", "gurugram", "noida", "greater noida", "ghaziabad", "faridabad", "ncr"],
    "remote_priority_geographies": ["united states", "us", "usa", "uk", "united kingdom", "middle east", "uae", "saudi", "qatar", "singapore", "australia"],
    "preferred_remote": ["remote", "hybrid"],
    "preferred_seniority": ["vp", "director", "associate partner", "partner", "practice head", "lead"],
    "min_experience_years": {"full_time": 12, "full_time_preferred": 15},
    "salary_expectation_inr_lpa": {"min": 60, "max": 200},
    "freelance_min_value_inr": 100000,
    "freelance_min_hourly_rate_inr": 5000,
    "certifications": [
        "World Bank Procurement",
        "PMP (Project Management Professional)",
        "PRINCE2 Practitioner",
        "Agile / Scrum Master",
    ],
    "languages": ["English", "Hindi"],
    "education": [
        {"degree": "MBA / Post Graduate Management", "field": "Strategy / Operations / Public Policy"},
        {"degree": "Bachelor's", "field": "Engineering / Technology"},
    ],
    "notable_projects": [
        {
            "name": "AP Health System Strengthening Project",
            "sector": "Digital Health",
            "funder": "World Bank",
            "skills": ["HMIS", "EHR", "Health Systems", "World Bank Procurement", "Government Health Advisory"],
            "description": "Led digital health systems strengthening and HMIS/EHR rollout under a World Bank-funded state health programme.",
        },
        {
            "name": "State e-Governance PMU",
            "sector": "Smart Governance",
            "funder": "State Government",
            "skills": ["PMU Setup", "Programme Management", "Citizen Services", "Digital Transformation"],
            "description": "Set up and led the Programme Management Unit for a state-wide e-governance and citizen services digital transformation initiative.",
        },
        {
            "name": "Power Sector Reform Advisory",
            "sector": "Power Sector",
            "funder": "ADB",
            "skills": ["Policy Advisory", "Procurement Advisory", "DPR Preparation", "Infrastructure"],
            "description": "Provided technical advisory and DPR preparation support for power distribution reform under an ADB-financed programme.",
        },
        {
            "name": "Postal Modernization Programme",
            "sector": "Postal Modernization",
            "funder": "Government of India",
            "skills": ["Business Process Reengineering", "Technology Advisory", "Change Management"],
            "description": "Advised on technology modernization and business process reengineering for postal services digitization.",
        },
        {
            "name": "Policing Modernization Initiative",
            "sector": "Policing",
            "funder": "State Government",
            "skills": ["Smart Governance", "Technology Advisory", "Vendor Management"],
            "description": "Supported technology-led policing modernization, including vendor evaluation and technical assessment.",
        },
        {
            "name": "Public Finance Management Reform",
            "sector": "Public Finance",
            "funder": "World Bank / JICA",
            "skills": ["Public Financial Management", "Procurement Advisory", "M&E", "Bid Management"],
            "description": "Advised on public financial management reforms and bid/procurement management for a multilateral-funded PFM programme.",
        },
    ],
    "keywords_high_priority": [
        "government consulting", "public sector advisory", "digital transformation",
        "ai governance", "ai-led governance", "pmu", "programme management",
        "procurement advisory", "bid management", "dpr", "rfp", "technical evaluation",
        "vendor management", "world bank", "adb", "jica", "aiib", "multilateral",
        "digital health", "public finance", "smart governance", "power sector",
        "policing", "postal modernization", "practice head", "associate partner",
    ],
    "keywords_medium_priority": [
        "project management", "stakeholder management", "m&e", "monitoring evaluation",
        "capacity building", "change management", "business development",
        "proposal management", "public sector", "policy", "strategy", "consulting",
        "director", "leadership", "infrastructure",
    ],
    "keywords_negative": [
        "entry level", "junior", "fresher", "0-2 years", "1-3 years", "3-5 years",
        "intern", "internship", "sales executive", "cold calling", "bpo",
        "call center", "data entry", "virtual assistant",
    ],
    "sector_weights": {
        "digital_health": 1.0,
        "smart_governance": 1.0,
        "government_consulting": 1.0,
        "public_finance": 0.95,
        "infrastructure": 0.9,
        "power_sector": 0.9,
        "policing": 0.85,
        "postal_modernization": 0.85,
        "digital_transformation": 1.0,
        "development_sector": 0.95,
        "it_consulting": 0.8,
        "social_sector": 0.75,
        "healthcare": 0.75,
        "education": 0.65,
        "finance": 0.6,
        "private_sector_generic": 0.4,
    },
}
