"""
Candidate profile constant for the senior consulting professional.
Used across AI matching, scoring, and recommendation services.
"""

CANDIDATE_PROFILE = {
    "name": "Senior Consulting Professional",
    "years_experience": 14,
    "summary": (
        "Senior consulting professional with 14+ years of experience spanning "
        "Project Management, Digital Transformation, Government Consulting, "
        "Public Health, E-Governance, IT Consulting, and Program/Project "
        "Management Unit (PMU/TSU) leadership. Proven track record delivering "
        "complex multi-stakeholder programs for World Bank, multilateral donors, "
        "and central/state government clients. Deep expertise in AI governance, "
        "health systems strengthening, and large-scale digital public infrastructure."
    ),
    "core_competencies": [
        "Project Management (PMP, PRINCE2)",
        "Digital Transformation Strategy",
        "E-Governance & Digital Public Infrastructure",
        "Government Consulting & Policy Advisory",
        "Public Health Systems Strengthening",
        "Program Management Unit (PMU) Leadership",
        "Technical Support Unit (TSU) Governance",
        "World Bank / Multilateral Project Management",
        "AI Governance & Responsible AI Frameworks",
        "IT Consulting & Technology Strategy",
        "Stakeholder Management & Facilitation",
        "Monitoring & Evaluation (M&E)",
        "Results-Based Management (RBM)",
        "Change Management",
        "Capacity Building & Training",
        "Business Process Reengineering",
        "Data Governance & Analytics",
        "Public Sector Reforms",
        "Health Information Systems (HIS/HMIS)",
        "Social Sector Consulting",
    ],
    "technical_skills": [
        "Python",
        "SQL",
        "Power BI",
        "Tableau",
        "MS Project",
        "Jira",
        "Confluence",
        "SharePoint",
        "SAP",
        "GIS / QGIS",
        "OpenMRS",
        "DHIS2",
        "ServiceNow",
        "Salesforce",
        "Azure DevOps",
        "AI / Machine Learning frameworks (conceptual & governance)",
        "Blockchain for public sector (conceptual)",
        "Cloud platforms (AWS, Azure, GCP — project oversight)",
    ],
    "domain_expertise": [
        "Digital Transformation",
        "E-Governance",
        "Public Health",
        "Health Systems",
        "Government IT",
        "Development Sector",
        "Social Protection",
        "Education Technology",
        "Smart Cities",
        "Financial Inclusion",
        "Agriculture Technology",
        "Disaster Management & Resilience",
        "Climate & Sustainability Programs",
        "Public Financial Management",
        "Citizen Services Delivery",
    ],
    "preferred_employers": [
        "World Bank",
        "UNDP",
        "UN Agencies",
        "ADB",
        "USAID",
        "GIZ",
        "DFID / FCDO",
        "Gates Foundation",
        "Deloitte",
        "PwC",
        "EY",
        "KPMG",
        "McKinsey",
        "BCG",
        "Accenture",
        "IBM Consulting",
        "Wipro",
        "TCS",
        "Infosys Consulting",
        "National Health Mission",
        "Ministry of Health",
        "MeitY",
        "NIC",
        "State Governments",
        "NASSCOM",
    ],
    "preferred_roles": [
        "Program Director",
        "Program Manager",
        "Project Director",
        "PMO Lead",
        "PMO Head",
        "Digital Transformation Lead",
        "Digital Transformation Director",
        "E-Governance Consultant",
        "Government Consulting Lead",
        "Senior Consultant",
        "Principal Consultant",
        "Practice Head",
        "Engagement Manager",
        "Client Partner",
        "Health Systems Specialist",
        "Public Health Advisor",
        "AI Governance Lead",
        "Technology Strategy Lead",
        "CTO (NGO / Social Sector)",
        "Chief Digital Officer",
        "VP Consulting",
    ],
    "preferred_locations": [
        "India",
        "Delhi NCR",
        "Mumbai",
        "Bangalore",
        "Hyderabad",
        "Remote",
        "Southeast Asia",
        "South Asia",
        "Africa (select)",
        "Washington DC",
        "Geneva",
        "New York",
    ],
    "preferred_remote": ["remote", "hybrid", "onsite"],
    "preferred_seniority": ["senior", "lead", "director", "vp", "principal", "head"],
    "salary_expectation_inr_lpa": {"min": 40, "max": 120},
    "salary_expectation_usd_annual": {"min": 80000, "max": 200000},
    "certifications": [
        "PMP (Project Management Professional)",
        "PRINCE2 Practitioner",
        "Agile / Scrum Master",
        "ITIL Foundation",
        "World Bank Procurement",
        "Google Project Management Certificate",
    ],
    "languages": ["English", "Hindi"],
    "education": [
        {
            "degree": "MBA / Post Graduate Management",
            "field": "Strategy / Operations / Public Policy",
        },
        {
            "degree": "Bachelor's",
            "field": "Engineering / Computer Science / Life Sciences",
        },
    ],
    "keywords_high_priority": [
        "digital transformation",
        "e-governance",
        "government consulting",
        "public health",
        "health systems",
        "PMO",
        "program director",
        "multilateral",
        "World Bank",
        "UNDP",
        "UN",
        "ADB",
        "development sector",
        "AI governance",
        "smart cities",
        "HMIS",
        "DHIS2",
        "health information",
        "social sector",
        "technology consulting",
    ],
    "keywords_medium_priority": [
        "project management",
        "stakeholder management",
        "M&E",
        "monitoring evaluation",
        "capacity building",
        "change management",
        "agile",
        "data governance",
        "public sector",
        "policy",
        "strategy",
        "consulting",
        "senior manager",
        "director",
        "leadership",
    ],
    "keywords_negative": [
        "entry level",
        "junior",
        "fresher",
        "0-2 years",
        "1-3 years",
        "intern",
        "internship",
        "sales executive",
        "cold calling",
        "BPO",
        "call center",
        "data entry",
    ],
    "sector_weights": {
        "digital_transformation": 1.0,
        "e_governance": 1.0,
        "public_health": 0.95,
        "development_sector": 0.95,
        "government_consulting": 1.0,
        "it_consulting": 0.85,
        "social_sector": 0.85,
        "healthcare": 0.80,
        "education": 0.75,
        "finance": 0.60,
        "private_sector_generic": 0.50,
    },
}
