import asyncio
from datetime import datetime, timezone, timedelta
from typing import Optional, List, Dict, Any
import httpx
from jinja2 import Environment, DictLoader
from app.core.config import settings
from app.core.logging_config import logger


# --- Jinja2 Email Templates ---

EMAIL_DIGEST_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
  body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 700px; margin: 0 auto; }
  .header { background: #1a365d; color: white; padding: 20px 30px; }
  .header h1 { margin: 0; font-size: 22px; }
  .header p { margin: 5px 0 0; opacity: 0.8; font-size: 14px; }
  .content { padding: 20px 30px; }
  .job-card { border: 1px solid #e2e8f0; border-radius: 8px; padding: 15px; margin: 15px 0; }
  .job-card h3 { margin: 0 0 5px; color: #2d3748; }
  .job-meta { font-size: 13px; color: #718096; margin: 5px 0; }
  .score-badge { display: inline-block; background: #48bb78; color: white; padding: 3px 10px; border-radius: 12px; font-size: 12px; font-weight: bold; }
  .score-high { background: #48bb78; }
  .score-med { background: #ed8936; }
  .score-low { background: #a0aec0; }
  .why-relevant { background: #f7fafc; border-left: 3px solid #4299e1; padding: 8px 12px; margin: 8px 0; font-size: 13px; }
  .apply-btn { display: inline-block; background: #4299e1; color: white; padding: 8px 20px; border-radius: 6px; text-decoration: none; font-size: 13px; margin-top: 8px; }
  .footer { background: #f7fafc; padding: 15px 30px; font-size: 12px; color: #a0aec0; text-align: center; }
  .summary-box { background: #ebf8ff; border: 1px solid #bee3f8; border-radius: 8px; padding: 15px; margin-bottom: 20px; }
</style>
</head>
<body>
<div class="header">
  <h1>Job Intelligence Digest</h1>
  <p>{{ date_str }} &bull; {{ total_jobs }} new opportunities found</p>
</div>
<div class="content">
  <div class="summary-box">
    <strong>Today's Summary:</strong> Found <strong>{{ total_jobs }}</strong> high-relevance opportunities.
    {% if top_score %}Top match score: <strong>{{ top_score }}%</strong>{% endif %}
    &bull; Sources: {{ sources_summary }}
  </div>

  {% for job in jobs %}
  <div class="job-card">
    <h3>{{ job.title }}</h3>
    <div class="job-meta">
      🏢 {{ job.company }}
      {% if job.location %} &bull; 📍 {{ job.location }}{% endif %}
      {% if job.remote_type %} &bull; 🌐 {{ job.remote_type | title }}{% endif %}
      {% if job.posted_date %} &bull; 📅 {{ job.posted_date }}{% endif %}
    </div>
    {% if job.match_score %}
    <span class="score-badge {% if job.match_score >= 80 %}score-high{% elif job.match_score >= 65 %}score-med{% else %}score-low{% endif %}">
      {{ job.match_score | round | int }}% Match
    </span>
    {% endif %}
    {% if job.ai_summary %}
    <p style="font-size: 13px; margin: 10px 0 5px;">{{ job.ai_summary }}</p>
    {% endif %}
    {% if job.why_relevant %}
    <div class="why-relevant">💡 {{ job.why_relevant }}</div>
    {% endif %}
    {% if job.source_url %}
    <a href="{{ job.source_url }}" class="apply-btn">View Job →</a>
    {% endif %}
  </div>
  {% endfor %}

  {% if insights %}
  <div style="margin-top: 25px; padding: 15px; background: #fffbeb; border: 1px solid #fbd38d; border-radius: 8px;">
    <strong>📊 Market Insight:</strong> {{ insights }}
  </div>
  {% endif %}
</div>
<div class="footer">
  <p>Job Intelligence Agent &bull; Unsubscribe | Preferences</p>
  <p>This digest was generated by AI based on your profile. <a href="{{ frontend_url }}">Manage preferences</a></p>
</div>
</body>
</html>
"""

TELEGRAM_DIGEST_TEMPLATE = """
🎯 *Job Intelligence Digest* — {{ date_str }}

Found *{{ total_jobs }}* new opportunities for you today.

{% for job in jobs[:5] %}
━━━━━━━━━━━━━━
🏢 *{{ job.title }}*
{{ job.company }} {% if job.location %}| 📍 {{ job.location }}{% endif %}
{% if job.match_score %}⭐ {{ job.match_score | round | int }}% match{% endif %}
{% if job.source_url %}[View Job]({{ job.source_url }}){% endif %}

{% endfor %}
{% if total_jobs > 5 %}
...and {{ total_jobs - 5 }} more. [See all →]({{ frontend_url }}/jobs)
{% endif %}
"""

jinja_env = Environment(
    loader=DictLoader({
        "email_digest": EMAIL_DIGEST_TEMPLATE,
        "telegram_digest": TELEGRAM_DIGEST_TEMPLATE,
    }),
    autoescape=True,
)


class NotificationService:
    def __init__(self, db=None):
        self.db = db

    async def send_email_digest(
        self,
        user: Any,
        jobs: List[Any],
    ) -> bool:
        """Send an HTML email digest to the user."""
        if not settings.EMAIL_NOTIFICATIONS_ENABLED:
            logger.info("Email notifications disabled, skipping digest")
            return False

        if not settings.SMTP_USERNAME or not settings.SMTP_PASSWORD:
            logger.warning("SMTP credentials not configured, skipping email digest")
            return False

        try:
            import emails
            from emails.template import JinjaTemplate

            date_str = datetime.now(timezone.utc).strftime("%B %d, %Y")
            top_score = None

            job_dicts = []
            sources = set()
            for job in jobs:
                score = getattr(job, "match_score", None) or (job.get("match_score") if isinstance(job, dict) else None)
                if score and (top_score is None or score > top_score):
                    top_score = round(score)
                j_dict = {
                    "title": getattr(job, "title", job.get("title", "") if isinstance(job, dict) else ""),
                    "company": getattr(job, "company", job.get("company", "") if isinstance(job, dict) else ""),
                    "location": getattr(job, "location", job.get("location") if isinstance(job, dict) else None),
                    "remote_type": getattr(job, "remote_type", job.get("remote_type") if isinstance(job, dict) else None),
                    "match_score": score,
                    "ai_summary": getattr(job, "ai_summary", job.get("ai_summary") if isinstance(job, dict) else None),
                    "why_relevant": getattr(job, "why_relevant", job.get("why_relevant") if isinstance(job, dict) else None),
                    "source_url": getattr(job, "source_url", job.get("source_url") if isinstance(job, dict) else None),
                    "posted_date": str(getattr(job, "posted_date", "")) or None,
                    "source_platform": getattr(job, "source_platform", job.get("source_platform") if isinstance(job, dict) else None),
                }
                job_dicts.append(j_dict)
                if j_dict["source_platform"]:
                    sources.add(j_dict["source_platform"])

            template = jinja_env.get_template("email_digest")
            html_body = template.render(
                date_str=date_str,
                total_jobs=len(jobs),
                jobs=job_dicts,
                top_score=top_score,
                sources_summary=", ".join(sources) or "Multiple platforms",
                insights=None,
                frontend_url=settings.FRONTEND_URL,
            )

            message = emails.Message(
                subject=f"Job Digest: {len(jobs)} new opportunities — {date_str}",
                html=html_body,
                mail_from=(settings.EMAIL_FROM_NAME, settings.EMAIL_FROM),
            )

            smtp_params = {
                "host": settings.SMTP_HOST,
                "port": settings.SMTP_PORT,
                "user": settings.SMTP_USERNAME,
                "password": settings.SMTP_PASSWORD,
                "tls": settings.SMTP_USE_TLS,
                "timeout": 15,
            }

            user_email = getattr(user, "email", None)
            if not user_email:
                logger.error("User has no email address")
                return False

            loop = asyncio.get_event_loop()
            response = await loop.run_in_executor(
                None,
                lambda: message.send(to=user_email, smtp=smtp_params),
            )

            if response.status_code == 250:
                logger.info(f"Email digest sent to {user_email}, {len(jobs)} jobs")
                self._log_notification(user, "email", len(jobs), "sent")
                return True
            else:
                logger.error(f"Email send failed with status {response.status_code}")
                return False

        except Exception as e:
            logger.error(f"Email digest failed: {e}")
            return False

    async def send_telegram_message(
        self,
        chat_id: str,
        message: str,
        parse_mode: str = "Markdown",
    ) -> bool:
        """Send a Telegram message via Bot API."""
        if not settings.TELEGRAM_BOT_TOKEN:
            logger.warning("Telegram bot token not configured")
            return False

        url = f"https://api.telegram.org/bot{settings.TELEGRAM_BOT_TOKEN}/sendMessage"
        payload = {
            "chat_id": chat_id,
            "text": message,
            "parse_mode": parse_mode,
            "disable_web_page_preview": False,
        }

        try:
            async with httpx.AsyncClient(timeout=15) as client:
                response = await client.post(url, json=payload)
                if response.status_code == 200:
                    logger.info(f"Telegram message sent to chat_id {chat_id}")
                    return True
                else:
                    logger.error(f"Telegram API error {response.status_code}: {response.text}")
                    return False
        except Exception as e:
            logger.error(f"Telegram send failed: {e}")
            return False

    async def send_telegram_digest(self, user: Any, jobs: List[Any]) -> bool:
        """Send a formatted digest via Telegram."""
        if not settings.TELEGRAM_NOTIFICATIONS_ENABLED:
            return False

        chat_id = getattr(user, "telegram_chat_id", None)
        if not chat_id:
            return False

        job_dicts = []
        for job in jobs:
            score = getattr(job, "match_score", None)
            j_dict = {
                "title": getattr(job, "title", ""),
                "company": getattr(job, "company", ""),
                "location": getattr(job, "location", None),
                "match_score": score,
                "source_url": getattr(job, "source_url", None),
            }
            job_dicts.append(j_dict)

        template = jinja_env.get_template("telegram_digest")
        message = template.render(
            date_str=datetime.now(timezone.utc).strftime("%b %d"),
            total_jobs=len(jobs),
            jobs=job_dicts,
            frontend_url=settings.FRONTEND_URL,
        )

        return await self.send_telegram_message(chat_id=chat_id, message=message)

    async def compile_daily_digest(self) -> Dict[str, Any]:
        """Compile digest data for all active users."""
        if not self.db:
            raise ValueError("Database session required for compile_daily_digest")

        from sqlalchemy import select
        from app.models.user import User
        from app.models.job import Job

        since = datetime.now(timezone.utc) - timedelta(hours=24)

        result = await self.db.execute(
            select(User).where(User.is_active == True)
        )
        users = result.scalars().all()

        job_result = await self.db.execute(
            select(Job)
            .where(
                Job.is_active == True,
                Job.scraped_at >= since,
                Job.match_score >= 60,
            )
            .order_by(Job.match_score.desc())
            .limit(20)
        )
        jobs = job_result.scalars().all()

        sent_count = 0
        for user in users:
            prefs = user.notification_preferences or {}
            if prefs.get("email_digest", True):
                min_score = prefs.get("min_score_threshold", 60)
                user_jobs = [j for j in jobs if (j.match_score or 0) >= min_score]
                if user_jobs:
                    await self.send_email_digest(user=user, jobs=user_jobs)
                    sent_count += 1

            if prefs.get("telegram", False) and user.telegram_chat_id:
                await self.send_telegram_digest(user=user, jobs=jobs[:5])

        return {"users_notified": sent_count, "jobs_in_digest": len(jobs)}

    def _log_notification(self, user: Any, notif_type: str, jobs_count: int, status: str):
        """Log notification to user preferences (in-memory, commit handled by caller)."""
        if not user or not self.db:
            return
        prefs = getattr(user, "preferences", {}) or {}
        history = prefs.get("notification_history", [])
        history.append({
            "type": notif_type,
            "subject": f"Job Digest — {jobs_count} jobs",
            "sent_at": datetime.now(timezone.utc).isoformat(),
            "jobs_count": jobs_count,
            "status": status,
        })
        prefs["notification_history"] = history[-100:]  # Keep last 100
        user.preferences = prefs


# Type alias for type hints
from typing import Any
